<?php
/**
 * Plugin Name: Loon & Hearth Staff Connector
 * Description: Private staff app access, order management and Firebase notifications.
 * Version: 1.0.0
 * Requires PHP: 8.0
 * Requires Plugins: woocommerce
 */
if (!defined('ABSPATH')) exit;
final class LH_Staff {
 const NS='lh-staff/v1';
 static function table(){global $wpdb; return $wpdb->prefix.'lh_staff_devices';}
 static function install(){global $wpdb; require_once ABSPATH.'wp-admin/includes/upgrade.php'; dbDelta('CREATE TABLE '.self::table()." (id bigint unsigned NOT NULL AUTO_INCREMENT, token_hash varchar(64) NOT NULL, user_id bigint unsigned NOT NULL, label varchar(120) NOT NULL, fcm_token text NULL, created datetime NOT NULL, last_seen datetime NOT NULL, PRIMARY KEY (id), UNIQUE KEY token_hash (token_hash)) ".$wpdb->get_charset_collate().';');}
 static function error($text,$status=400){return new WP_Error('lh_staff_error',$text,['status'=>$status]);}
 static function auth($r){global $wpdb; if(!is_ssl()) return self::error('HTTPS is required.',403); $bearer=$r->get_header('authorization'); if(!preg_match('/^Bearer ([a-f0-9]{64})$/',$bearer,$m))return self::error('Please sign in.',401); $device=$wpdb->get_row($wpdb->prepare('SELECT * FROM '.self::table().' WHERE token_hash=%s',hash('sha256',$m[1]))); if(!$device || !user_can($device->user_id,'manage_woocommerce'))return self::error('Device access was revoked. Sign in again.',401); wp_set_current_user($device->user_id); $r->set_param('_staff_device',$device); $wpdb->update(self::table(),['last_seen'=>current_time('mysql',true)],['id'=>$device->id]); return true;}
 static function routes(){
 register_rest_route(self::NS,'/login',['methods'=>'POST','permission_callback'=>'__return_true','callback'=>[self::class,'login']]);
 foreach(['/orders'=>['GET','orders'],'/orders/(?P<id>\d+)'=>['GET','detail'],'/orders/(?P<id>\d+)/status'=>['POST','status'],'/orders/(?P<id>\d+)/refund'=>['POST','refund'],'/device'=>['POST','device'],'/logout'=>['POST','logout'],'/config'=>['GET','config']] as $path=>$v)register_rest_route(self::NS,$path,['methods'=>$v[0],'permission_callback'=>[self::class,'auth'],'callback'=>[self::class,$v[1]]]);
 }
 static function login($r){
 if(!is_ssl())return self::error('HTTPS is required.',403);
 // Atomic per-IP fixed-window rate limit; no forwarding header is trusted.
 global $wpdb; $bucket='lhs_attempt_'.hash('sha256',($_SERVER['REMOTE_ADDR']??'unknown').'|'.floor(time()/900));
 add_option($bucket,0,'','no'); $wpdb->query($wpdb->prepare("UPDATE {$wpdb->options} SET option_value=CAST(option_value AS UNSIGNED)+1 WHERE option_name=%s",$bucket)); $count=(int)$wpdb->get_var($wpdb->prepare("SELECT option_value FROM {$wpdb->options} WHERE option_name=%s",$bucket));
 if($count>5)return self::error('Too many attempts. Wait 15 minutes.',429);
 $pin=(string)$r->get_param('pin'); $uid=(int)get_option('lhs_staff_user'); $hash=get_option('lhs_pin_hash','');
 if(!preg_match('/^\d{8,12}$/',$pin)||!$hash||!wp_check_password($pin,$hash)||!user_can($uid,'manage_woocommerce'))return self::error('Incorrect PIN or staff access unavailable.',401);
 $token=bin2hex(random_bytes(32)); $ok=$wpdb->insert(self::table(),['token_hash'=>hash('sha256',$token),'user_id'=>$uid,'label'=>substr(sanitize_text_field($r->get_param('label')?:'Android device'),0,120),'created'=>current_time('mysql',true),'last_seen'=>current_time('mysql',true)]);
 if(!$ok)return self::error('Could not register device.',500); return ['token'=>$token,'site_name'=>get_bloginfo('name')];
 }
 static function record($o,$detail=false){
 $gateways=WC()->payment_gateways()->payment_gateways(); $g=$gateways[$o->get_payment_method()]??null;
 $data=['id'=>$o->get_id(),'number'=>$o->get_order_number(),'status'=>$o->get_status(),'status_label'=>wc_get_order_status_name($o->get_status()),'customer'=>trim($o->get_billing_first_name().' '.$o->get_billing_last_name()),'total'=>$o->get_total(),'currency'=>$o->get_currency(),'payment'=>$o->get_payment_method_title(),'payment_id'=>$o->get_payment_method(),'date'=>$o->get_date_created()?->date('c'),'remaining_refund'=>wc_format_decimal($o->get_remaining_refund_amount(),2),'paid'=>(bool)$o->get_date_paid(),'gateway_refund'=>(bool)($g && $g->supports('refunds') && $g->can_refund_order($o))];
 if($detail){$data['email']=$o->get_billing_email();$data['phone']=$o->get_billing_phone();$data['customer_note']=$o->get_customer_note();$data['items']=[];foreach($o->get_items() as $i)$data['items'][]=['name'=>$i->get_name(),'quantity'=>$i->get_quantity(),'total'=>$i->get_total()]; $data['shipping']=$o->get_shipping_method(); $data['refunded']=$o->get_total_refunded(); $data['fees']=[];foreach($o->get_fees() as $i)$data['fees'][]=['name'=>$i->get_name(),'total'=>$i->get_total()];}
 return $data;
 }
 static function orders($r){$args=['limit'=>30,'page'=>max(1,(int)$r->get_param('page')),'orderby'=>'date','order'=>'DESC','paginate'=>true,'type'=>'shop_order'];$s=sanitize_key($r->get_param('status')?:'');if($s&&isset(wc_get_order_statuses()['wc-'.$s]))$args['status']=$s;$result=wc_get_orders($args);return ['orders'=>array_map(fn($o)=>self::record($o),$result->orders),'pages'=>$result->max_num_pages];}
 static function order($r){$o=wc_get_order((int)$r['id']);return ($o instanceof WC_Order)?$o:null;}
 static function detail($r){$o=self::order($r);return $o?self::record($o,true):self::error('Order not found.',404);}
 static function lock($id){return add_option('lhs_lock_'.$id,time(),'','no');}
 static function unlock($id){delete_option('lhs_lock_'.$id);}
 static function status($r){$o=self::order($r);if(!$o)return self::error('Order not found.',404);$s=sanitize_key($r->get_param('status'));if(!in_array($s,['pending','on-hold','processing','completed','cancelled'],true))return self::error('Unsupported status. Use Refund for refunds.');if(!self::lock($o->get_id()))return self::error('This order is busy. Ask an administrator if this persists.',409);
 try{$o=wc_get_order($o->get_id());if($o->get_status()!==(string)$r->get_param('expected_status'))return self::error('Order changed. Refresh first.',409);if(in_array($o->get_status(),['refunded','cancelled'],true))return self::error('Closed orders must be handled in WordPress.');$o->update_status($s,'Updated from staff Android app by '.wp_get_current_user()->user_login,true);return self::record($o,true);}finally{self::unlock($o->get_id());}}
 static function refund($r){$o=self::order($r);if(!$o)return self::error('Order not found.',404);$key=(string)$r->get_param('request_id');if(!preg_match('/^[a-f0-9-]{36}$/',$key))return self::error('A refund request ID is required.');if(!self::lock($o->get_id()))return self::error('Order busy. Refresh; do not retry a refund blindly.',409);
 try{$o=wc_get_order($o->get_id());$history=$o->get_meta('_lhs_refunds')?:[];if(isset($history[$key]))return self::error('This refund request was already submitted. Check order history before retrying.',409);
 foreach($history as $previous){if(in_array($previous['state']??'',['submitted','needs_review'],true))return self::error('A previous refund needs administrator review before another refund.',409);}
 $raw=(string)$r->get_param('amount');if(!preg_match('/^\d+(\.\d{1,2})?$/',$raw))return self::error('Use a positive amount with up to two decimal places.');$amount=(float)$raw;if($amount<=0||$amount>(float)$o->get_remaining_refund_amount())return self::error('Amount exceeds the refundable balance.');$mode=$r->get_param('mode');$reason=substr(sanitize_textarea_field($r->get_param('reason')),0,500);if(!$reason)return self::error('Please enter a refund reason.');$manual=in_array($o->get_payment_method(),['bacs','cod'],true);
 if($mode==='gateway'){ $g=WC()->payment_gateways()->payment_gateways()[$o->get_payment_method()]??null;if(!$o->get_date_paid()||!$g||!$g->supports('refunds')||!$g->can_refund_order($o))return self::error('Automatic refund unavailable. Use WordPress or the processor dashboard.'); }
 elseif($mode==='manual'){if(!$manual||!$r->get_param('money_returned'))return self::error('Manual refund requires cash/e-transfer and confirmation that money was returned.');}else return self::error('Select refund method.');
 $history[$key]=['state'=>'submitted','amount'=>$raw,'staff'=>get_current_user_id(),'time'=>time()];$o->update_meta_data('_lhs_refunds',$history);$o->save();
 $refund=wc_create_refund(['order_id'=>$o->get_id(),'amount'=>$amount,'reason'=>$reason,'refund_payment'=>$mode==='gateway','restock_items'=>false]);
 if(is_wp_error($refund)){$history[$key]['state']='needs_review';$o->update_meta_data('_lhs_refunds',$history);$o->add_order_note('Staff refund needs review: '.$refund->get_error_message());$o->save();return self::error('Refund could not be confirmed. Check WooCommerce and the payment processor before another attempt.',502);}
 $history[$key]['state']='completed';$history[$key]['refund_id']=$refund->get_id();$o=wc_get_order($o->get_id());$o->update_meta_data('_lhs_refunds',$history);$o->add_order_note('Staff app '.($mode==='gateway'?'gateway refund':'manual refund recorded; staff confirmed money returned').' by '.wp_get_current_user()->user_login.'. No inventory restocked.');$o->save();return self::record($o,true);
 }finally{self::unlock($o->get_id());}}
 static function device($r){global $wpdb;$token=(string)$r->get_param('fcm_token');if(strlen($token)>4096)return self::error('Invalid push token.');$wpdb->update(self::table(),['fcm_token'=>$token],['id'=>$r->get_param('_staff_device')->id]);return ['ok'=>true];}
 static function logout($r){global $wpdb;$wpdb->delete(self::table(),['id'=>$r->get_param('_staff_device')->id]);return ['ok'=>true];}
 static function config(){return ['update_url'=>esc_url_raw(get_option('lhs_update_url','')),'statuses'=>['pending'=>'Pending payment','on-hold'=>'On hold','processing'=>'Processing','completed'=>'Completed','cancelled'=>'Cancelled']];}
 static function queue($id){if(!wc_get_order($id))return;if(function_exists('as_enqueue_async_action'))as_enqueue_async_action('lhs_send_push',['order_id'=>$id],'lh-staff',true);else wp_schedule_single_event(time()+5,'lhs_send_push',[$id]);}
 static function push($id){global $wpdb;$o=wc_get_order($id);if(!$o||$o->get_meta('_lhs_push_sent'))return;$json=get_option('lhs_firebase_json','');$sa=json_decode($json,true);if(!$sa||empty($sa['private_key'])||empty($sa['project_id']))return;
 $access=get_transient('lhs_fcm_access');if(!$access){$b64=fn($s)=>rtrim(strtr(base64_encode($s),'+/','-_'),'=');$now=time();$jwt=$b64(wp_json_encode(['alg'=>'RS256','typ'=>'JWT'])).'.'.$b64(wp_json_encode(['iss'=>$sa['client_email'],'scope'=>'https://www.googleapis.com/auth/firebase.messaging','aud'=>'https://oauth2.googleapis.com/token','iat'=>$now,'exp'=>$now+3600]));if(!openssl_sign($jwt,$sig,$sa['private_key'],OPENSSL_ALGO_SHA256))return;$res=wp_remote_post('https://oauth2.googleapis.com/token',['timeout'=>15,'body'=>['grant_type'=>'urn:ietf:params:oauth:grant-type:jwt-bearer','assertion'=>$jwt.'.'.$b64($sig)]]);if(is_wp_error($res))return;$access=json_decode(wp_remote_retrieve_body($res),true)['access_token']??'';if(!$access)return;set_transient('lhs_fcm_access',$access,3000);}
 $devices=$wpdb->get_results('SELECT id,user_id,fcm_token FROM '.self::table()." WHERE fcm_token IS NOT NULL AND fcm_token<>''");$failed=false;
 foreach($devices as $d){if(!user_can($d->user_id,'manage_woocommerce')||$o->get_meta('_lhs_push_device_'.$d->id))continue;$res=wp_remote_post('https://fcm.googleapis.com/v1/projects/'.rawurlencode($sa['project_id']).'/messages:send',['timeout'=>15,'headers'=>['Authorization'=>'Bearer '.$access,'Content-Type'=>'application/json'],'body'=>wp_json_encode(['message'=>['token'=>$d->fcm_token,'data'=>['order_id'=>(string)$id,'title'=>'New Loon & Hearth order','body'=>'An order is ready to review.'],'android'=>['priority'=>'high']]])]);$code=is_wp_error($res)?0:wp_remote_retrieve_response_code($res);$body=is_wp_error($res)?[]:json_decode(wp_remote_retrieve_body($res),true);$unregistered=false;foreach($body['error']['details']??[] as $e)if(($e['errorCode']??'')==='UNREGISTERED')$unregistered=true;if($unregistered){$wpdb->update(self::table(),['fcm_token'=>''],['id'=>$d->id]);continue;}if($code===200){$o->update_meta_data('_lhs_push_device_'.$d->id,time());$o->save();}else{$failed=true;if($code===401)delete_transient('lhs_fcm_access');}}
 if(!$failed){$o->update_meta_data('_lhs_push_sent',time());$o->save();}else{$attempt=(int)$o->get_meta('_lhs_push_attempts')+1;$o->update_meta_data('_lhs_push_attempts',$attempt);$o->save();if($attempt<5)wp_schedule_single_event(time()+60*$attempt,'lhs_send_push',[$id]);}
 }
 static function admin(){add_submenu_page('woocommerce','Staff Android App','Staff Android App','manage_options','lh-staff',[self::class,'settings']);}
 static function settings(){if(!current_user_can('manage_options'))return;global $wpdb;$notice='';
 if($_SERVER['REQUEST_METHOD']==='POST'){check_admin_referer('lhs_settings');if(isset($_POST['revoke'])){$wpdb->delete(self::table(),['id'=>absint($_POST['revoke'])]);$notice='Device revoked.';}else{$uid=absint($_POST['staff_user']);if(!user_can($uid,'manage_woocommerce')){$notice='Choose a user with order management permissions.';}else{$pin=trim(wp_unslash($_POST['pin']??''));if($pin && !preg_match('/^\d{8,12}$/',$pin))$notice='PIN must contain 8–12 digits.';else{if((int)get_option('lhs_staff_user')!==$uid)$wpdb->query('DELETE FROM '.self::table());update_option('lhs_staff_user',$uid,false);if($pin){update_option('lhs_pin_hash',wp_hash_password($pin),false);$wpdb->query('DELETE FROM '.self::table());$notice='PIN saved. Existing devices revoked.';} $url=esc_url_raw(wp_unslash($_POST['update_url']??''));if(!$url||preg_match('#^https://github\.com/[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+/releases/latest/download/update\.json$#',$url))update_option('lhs_update_url',$url,false);else $notice='Update URL must be a GitHub latest release update.json URL.';
 $firebase=trim(wp_unslash($_POST['firebase_json']??''));if($firebase){$sa=json_decode($firebase,true);if(isset($sa['project_id'],$sa['client_email'],$sa['private_key'])&&openssl_pkey_get_private($sa['private_key'])){update_option('lhs_firebase_json',$firebase,false);delete_transient('lhs_fcm_access');}else $notice='Invalid Firebase service-account JSON.';}if(!$notice)$notice='Settings saved.';}}}}
 echo '<div class="wrap"><h1>Loon & Hearth Staff App</h1><p>'.esc_html($notice).'</p><p>Server: <code>'.esc_html(home_url()).'</code>. PIN is entered once per device. Revocation immediately blocks API access. Changing the PIN revokes all devices.</p><form method="post">';wp_nonce_field('lhs_settings');echo '<p>Staff user ID <input required type="number" name="staff_user" value="'.absint(get_option('lhs_staff_user',get_current_user_id())).'"></p><p>New 8–12 digit PIN <input type="password" autocomplete="new-password" name="pin" pattern="[0-9]{8,12}"> Leave blank to preserve.</p><p>GitHub update manifest URL<br><input style="width:650px;max-width:100%" name="update_url" value="'.esc_attr(get_option('lhs_update_url','')).'"></p><p>Firebase service account JSON (server only; leave blank to preserve)<br><textarea name="firebase_json" rows="5" cols="80" autocomplete="off"></textarea></p><p>'.(get_option('lhs_firebase_json')?'Firebase credentials configured.':'Firebase not configured.').'</p>';submit_button('Save settings');echo '</form><h2>Authorized devices</h2>';
 foreach($wpdb->get_results('SELECT id,label,last_seen FROM '.self::table()) as $d){echo '<form method="post"><p>'.esc_html($d->label).' — last seen '.esc_html($d->last_seen).' UTC ';wp_nonce_field('lhs_settings');echo '<button class="button" name="revoke" value="'.absint($d->id).'">Revoke access</button></p></form>';}echo '<p>Refunds never restock meals automatically. Gateway errors require review before retrying. Use WooCommerce for item-level refunds or inventory restoration.</p></div>';
 }
}
register_activation_hook(__FILE__,[LH_Staff::class,'install']);
add_action('rest_api_init',[LH_Staff::class,'routes']);add_action('admin_menu',[LH_Staff::class,'admin']);add_action('woocommerce_checkout_order_processed',[LH_Staff::class,'queue'],20);add_action('woocommerce_store_api_checkout_order_processed',fn($o)=>LH_Staff::queue($o->get_id()),20);add_action('lhs_send_push',[LH_Staff::class,'push']);
add_filter('rest_post_dispatch',function($response,$server,$request){if(str_starts_with($request->get_route(),'/lh-staff/'))$response->header('Cache-Control','no-store, private');return $response;},10,3);
add_action('before_woocommerce_init',function(){if(class_exists('Automattic\\WooCommerce\\Utilities\\FeaturesUtil')) Automattic\WooCommerce\Utilities\FeaturesUtil::declare_compatibility('custom_order_tables',__FILE__,true);});

add_action('init',function(){if(!wp_next_scheduled('lhs_cleanup_attempts'))wp_schedule_event(time()+86400,'daily','lhs_cleanup_attempts');});
add_action('lhs_cleanup_attempts',function(){global $wpdb;$wpdb->query($wpdb->prepare("DELETE FROM {$wpdb->options} WHERE option_name LIKE %s",$wpdb->esc_like('lhs_attempt_').'%'));});
register_deactivation_hook(__FILE__,function(){wp_clear_scheduled_hook('lhs_cleanup_attempts');wp_clear_scheduled_hook('lhs_send_push');});
