package ca.loonandhearth.staff;
import android.Manifest;
import android.app.*;
import android.content.*;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.os.*;
import android.text.InputType;
import android.view.*;
import android.widget.*;
import com.google.firebase.messaging.FirebaseMessaging;
import org.json.*;
import java.util.UUID;
import java.util.concurrent.*;
public class MainActivity extends Activity {
 final int green=Color.rgb(23,75,56),ink=Color.rgb(31,44,37);LinearLayout root,content;TextView heading;final ExecutorService jobs=Executors.newSingleThreadExecutor();int page=1,pages=1,orderId=0;String filter="";boolean busy=false;String screen="";
 interface Job {JSONObject run()throws Exception;}interface Done{void run(JSONObject data)throws Exception;}
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(green);getWindow().setNavigationBarColor(Color.WHITE);frame();if(Vault.read(this).isEmpty())login();else{registerPush();int id=getIntent().getIntExtra("order_id",0);if(id>0)detail(id);else orders();checkUpdates(false);}}
 @Override protected void onNewIntent(Intent i){super.onNewIntent(i);setIntent(i);int id=i.getIntExtra("order_id",0);if(id>0&&!Vault.read(this).isEmpty())detail(id);}
 int dp(int x){return Math.round(x*getResources().getDisplayMetrics().density);}
 TextView text(String s,int size,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(ink);if(bold)t.setTypeface(null,Typeface.BOLD);t.setPadding(0,dp(5),0,dp(5));return t;}
 void frame(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(Color.rgb(246,247,242));root.setPadding(dp(18),0,dp(18),0);root.setOnApplyWindowInsetsListener((v,i)->{root.setPadding(dp(18),i.getSystemWindowInsetTop()+dp(10),dp(18),i.getSystemWindowInsetBottom());return i;});setContentView(root);heading=text("Loon & Hearth",26,true);root.addView(heading);ScrollView scroll=new ScrollView(this);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(0,dp(8),0,dp(24));scroll.addView(content);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));}
 void clear(String title){content.removeAllViews();heading.setText(title);screen=title;}
 Button button(String title,LinearLayout parent,Runnable click){Button b=new Button(this);b.setText(title);b.setAllCaps(false);b.setTextColor(Color.WHITE);GradientDrawable bg=new GradientDrawable();bg.setColor(green);bg.setCornerRadius(dp(12));b.setBackground(bg);var lp=new LinearLayout.LayoutParams(-1,dp(50));lp.setMargins(0,dp(6),0,dp(6));parent.addView(b,lp);b.setOnClickListener(v->{if(!busy)click.run();});return b;}
 EditText field(String hint,int type,LinearLayout box){EditText e=new EditText(this);e.setHint(hint);e.setTextSize(16);e.setInputType(type);e.setPadding(dp(10),dp(12),dp(10),dp(12));box.addView(e,new LinearLayout.LayoutParams(-1,-2));return e;}
 LinearLayout card(){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(16),dp(12),dp(16),dp(12));GradientDrawable bg=new GradientDrawable();bg.setColor(Color.WHITE);bg.setCornerRadius(dp(16));box.setBackground(bg);var lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,dp(8),0,dp(8));content.addView(box,lp);return box;}
 void task(Job job,Done done){if(busy)return;busy=true;String origin=screen;ProgressDialog spinner=ProgressDialog.show(this,"","Please wait…",true,false);jobs.execute(()->{try{JSONObject result=job.run();runOnUiThread(()->{busy=false;spinner.dismiss();if(isFinishing())return;try{done.run(result);}catch(Exception e){alert("Could not display response",e.getMessage());}});}catch(Exception e){runOnUiThread(()->{busy=false;spinner.dismiss();if(e instanceof Api.Failure && ((Api.Failure)e).code==401){Vault.clear(this);login();}alert("Request unsuccessful",e.getMessage()+"\n\nFor a refund or status change, refresh the order before trying again.");});}});}
 void alert(String title,String message){new AlertDialog.Builder(this).setTitle(title).setMessage(message).setPositiveButton("OK",null).show();}
 void login(){clear("Staff sign in");content.addView(text("Enter your staff PIN once. This device stays signed in until access is revoked or you sign out.",16,false));LinearLayout box=card();EditText site=field("Website",InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_URI,box);site.setText(Api.site(this));EditText pin=field("8–12 digit PIN",InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_VARIATION_PASSWORD,box);pin.setImportantForAutofill(View.IMPORTANT_FOR_AUTOFILL_NO);button("Sign in",box,()->{String url=site.getText().toString().trim().replaceAll("/+$","");if(!url.matches("https://[A-Za-z0-9.-]+(:443)?")){alert("Website","Enter an HTTPS website address without a path.");return;}getSharedPreferences("staff",0).edit().putString("site",url).apply();String code=pin.getText().toString();if(!code.matches("[0-9]{8,12}")){alert("PIN","Enter 8–12 digits.");return;}task(()->Api.call(this,"/login",new JSONObject().put("pin",code).put("label",Build.MANUFACTURER+" "+Build.MODEL)),data->{Vault.save(this,data.getString("token"));pin.setText("");registerPush();orders();});});}
 void registerPush(){PushService.channel(this);if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=android.content.pm.PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},101);if(!BuildConfig.PUSH_CONFIGURED)return;FirebaseMessaging.getInstance().getToken().addOnSuccessListener(t->{getSharedPreferences("staff",0).edit().putString("fcm",t).apply();jobs.execute(()->{try{Api.call(this,"/device",new JSONObject().put("fcm_token",t));}catch(Exception ignored){}});});}
 void orders(){orderId=0;clear("Orders");LinearLayout tools=card();tools.addView(text("Staff dashboard",18,true));String[] labels={"All orders","Pending payment","On hold","Processing","Completed","Cancelled","Refunded"};String[] keys={"","pending","on-hold","processing","completed","cancelled","refunded"};Spinner select=new Spinner(this);select.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,labels));for(int i=0;i<keys.length;i++)if(keys[i].equals(filter))select.setSelection(i);tools.addView(select);button("Refresh orders",tools,()->{filter=keys[select.getSelectedItemPosition()];page=1;orders();});button("Settings & updates",tools,this::settings);task(()->Api.call(this,"/orders?page="+page+"&status="+filter,null),data->{pages=data.getInt("pages");JSONArray list=data.getJSONArray("orders");if(list.length()==0)content.addView(text("No orders here yet.",17,false));for(int i=0;i<list.length();i++){JSONObject o=list.getJSONObject(i);LinearLayout box=card();box.addView(text("#"+o.getString("number")+" · "+o.getString("status_label"),18,true));box.addView(text(o.optString("customer","Customer"),16,false));box.addView(text(o.getString("currency")+" "+o.getString("total")+" · "+o.getString("payment"),15,false));box.addView(text(o.optString("date","").replace('T',' '),13,false));button("View order",box,()->detail(o.optInt("id")));}if(page>1)button("Previous page",content,()->{page--;orders();});if(page<pages)button("Next page",content,()->{page++;orders();});});}
 void detail(int id){orderId=id;clear("Order details");button("Back to orders",content,this::orders);task(()->Api.call(this,"/orders/"+id,null),o->renderOrder(o));}
 void renderOrder(JSONObject o)throws Exception{LinearLayout summary=card();summary.addView(text("Order #"+o.getString("number"),24,true));summary.addView(text(o.getString("status_label"),17,true));summary.addView(text(o.optString("customer")+"\n"+o.optString("email")+"\n"+o.optString("phone"),16,false));summary.addView(text("Payment: "+o.getString("payment")+"\nTotal: "+o.getString("currency")+" "+o.getString("total")+"\nRefunded: "+o.getString("refunded"),16,false));summary.addView(text("Fulfilment: "+o.optString("shipping","Pickup")+"\n"+o.optString("customer_note"),15,false));LinearLayout items=card();items.addView(text("Items",18,true));JSONArray a=o.getJSONArray("items");for(int i=0;i<a.length();i++){JSONObject item=a.getJSONObject(i);items.addView(text(item.getInt("quantity")+" × "+item.getString("name")+"  ·  "+item.getString("total"),16,false));}JSONArray fees=o.getJSONArray("fees");for(int i=0;i<fees.length();i++){JSONObject f=fees.getJSONObject(i);items.addView(text(f.getString("name")+": "+f.getString("total"),14,false));}button("Change status",content,()->statusDialog(o));if(o.optDouble("remaining_refund")>0)button("Refund",content,()->refundDialog(o));button("Refresh order",content,()->detail(orderId));}
 void statusDialog(JSONObject o){String[] names={"Pending payment","On hold","Processing","Completed","Cancelled"};String[] keys={"pending","on-hold","processing","completed","cancelled"};new AlertDialog.Builder(this).setTitle("Change order status").setItems(names,(d,index)->new AlertDialog.Builder(this).setTitle("Set "+names[index]+"?").setMessage("This updates WooCommerce and may send its usual customer email. Marking Processing does not charge a card.").setNegativeButton("Cancel",null).setPositiveButton("Confirm",(x,w)->task(()->Api.call(this,"/orders/"+orderId+"/status",new JSONObject().put("status",keys[index]).put("expected_status",o.getString("status"))),data->detail(orderId))).show()).show();}
 void refundDialog(JSONObject o){boolean manual=o.optString("payment_id").equals("cod")||o.optString("payment_id").equals("bacs");if(!manual&&!o.optBoolean("gateway_refund")){alert("Refund unavailable","This payment gateway cannot refund this order automatically. Use WooCommerce or your payment processor dashboard.");return;}LinearLayout form=new LinearLayout(this);form.setOrientation(LinearLayout.VERTICAL);form.setPadding(dp(20),dp(10),dp(20),dp(10));form.addView(text("Remaining: "+o.optString("currency")+" "+o.optString("remaining_refund")+"\n"+(manual?"Return the money manually first. This only records the refund.":"This sends a refund through the order’s payment gateway.")+"\nInventory will not be restocked.",16,false));EditText amount=field("Amount",InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL,form);EditText reason=field("Reason",InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_FLAG_MULTI_LINE,form);CheckBox returned=new CheckBox(this);returned.setText("I have returned the cash / e-transfer");if(manual)form.addView(returned);AlertDialog dialog=new AlertDialog.Builder(this).setTitle("Refund order #"+o.optString("number")).setView(form).setNegativeButton("Cancel",null).setPositiveButton("Review",null).create();dialog.setOnShowListener(x->dialog.getButton(-1).setOnClickListener(v->{String value=amount.getText().toString().trim(),why=reason.getText().toString().trim();if(!value.matches("[0-9]+(\\.[0-9]{1,2})?")||why.isEmpty()||(manual&&!returned.isChecked())){alert("Check refund","Enter an amount and reason, and confirm money returned for a manual refund.");return;}String requestId=UUID.randomUUID().toString();new AlertDialog.Builder(this).setTitle("Confirm refund "+o.optString("currency")+" "+value).setMessage("Order #"+o.optString("number")+"\n"+why+"\n\n"+(manual?"Record money already returned.":"Send money back via the payment gateway.")).setNegativeButton("Cancel",null).setPositiveButton("Confirm refund",(a,b)->{dialog.dismiss();task(()->Api.call(this,"/orders/"+orderId+"/refund",new JSONObject().put("amount",value).put("reason",why).put("mode",manual?"manual":"gateway").put("money_returned",manual).put("request_id",requestId)),data->detail(orderId));}).show();}));dialog.show();}
 void settings(){clear("Settings");content.addView(text("Loon & Hearth Staff · "+BuildConfig.VERSION_NAME+"\n"+Api.site(this),17,true));content.addView(text(BuildConfig.PUSH_CONFIGURED?"Push integration configured. Enable notifications in Android settings. Delivery requires the website’s Firebase credentials.":"Push notifications are not configured in this build. Add Firebase configuration and create a new release.",16,false));button("Notification settings",content,()->startActivity(new Intent("android.settings.APP_NOTIFICATION_SETTINGS").putExtra("android.provider.extra.APP_PACKAGE",getPackageName())));button("Check for updates",content,()->checkUpdates(true));button("Back to orders",content,this::orders);button("Sign out & revoke device",content,()->task(()->Api.call(this,"/logout",new JSONObject()),d->{Vault.clear(this);getSystemService(NotificationManager.class).cancelAll();login();}));}
 void checkUpdates(boolean visible){jobs.execute(()->{try{JSONObject cfg=Api.call(this,"/config",null);String url=cfg.optString("update_url");if(url.isEmpty()){if(visible)runOnUiThread(()->alert("Updates","Set the GitHub update URL in WooCommerce → Staff Android App."));return;}JSONObject manifest=Updater.manifest(url);if(manifest.getInt("versionCode")<=BuildConfig.VERSION_CODE){if(visible)runOnUiThread(()->alert("Updates","You have the latest version."));return;}runOnUiThread(()->new AlertDialog.Builder(this).setTitle("Update "+manifest.optString("versionName")).setMessage("Download and install the latest staff app? Android will ask you to confirm installation.").setNegativeButton("Later",null).setPositiveButton("Update",(d,w)->{task(()->{Updater.download(this,manifest);return new JSONObject();},r->Updater.install(this));}).show());}catch(Exception e){if(visible)runOnUiThread(()->alert("Update check failed",e.getMessage()));}});}
 @Override public void onBackPressed(){if(busy)return;if(!Vault.read(this).isEmpty()&&!screen.equals("Orders"))orders();else super.onBackPressed();}
 @Override protected void onDestroy(){jobs.shutdown();super.onDestroy();}
}
