package ca.loonandhearth.staff;
import android.app.Activity;
import android.content.*;
import android.content.pm.*;
import android.net.Uri;
import android.os.Build;
import androidx.core.content.FileProvider;
import org.json.JSONObject;
import java.io.*;
import java.net.*;
import java.security.MessageDigest;
import java.util.*;
final class Updater {
 static byte[] read(InputStream in,int max)throws IOException{ByteArrayOutputStream out=new ByteArrayOutputStream();byte[] b=new byte[8192];int n;while((n=in.read(b))!=-1){if(out.size()+n>max)throw new IOException("Response too large.");out.write(b,0,n);}return out.toByteArray();}
 static HttpURLConnection connect(String raw)throws Exception{for(int i=0;i<6;i++){URL u=new URL(raw);String h=u.getHost();if(!u.getProtocol().equals("https")||!(h.equals("github.com")||h.equals("release-assets.githubusercontent.com")||h.equals("objects.githubusercontent.com")))throw new IOException("Untrusted update location.");HttpURLConnection c=(HttpURLConnection)u.openConnection();c.setInstanceFollowRedirects(false);c.setConnectTimeout(15000);c.setReadTimeout(30000);int s=c.getResponseCode();if(s>=300&&s<400){String next=c.getHeaderField("Location");c.disconnect();raw=new URL(u,next).toString();continue;}if(s!=200){c.disconnect();throw new IOException("Update download failed ("+s+").");}return c;}throw new IOException("Too many redirects.");}
 static JSONObject manifest(String url)throws Exception{if(!url.matches("https://github\\.com/[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+/releases/latest/download/update\\.json"))throw new IOException("Invalid GitHub manifest URL.");HttpURLConnection c=connect(url);try(InputStream in=c.getInputStream()){JSONObject j=new JSONObject(new String(read(in,100000),java.nio.charset.StandardCharsets.UTF_8));if(!j.getString("packageName").equals("ca.loonandhearth.staff"))throw new IOException("Wrong application in update manifest.");return j;}finally{c.disconnect();}}
 static File apk(Context c){File dir=new File(c.getCacheDir(),"updates");dir.mkdirs();return new File(dir,"staff-update.apk");}
 static String hex(byte[] a){StringBuilder b=new StringBuilder();for(byte x:a)b.append(String.format(Locale.ROOT,"%02x",x&255));return b.toString();}
 @SuppressWarnings("deprecation") static Set<String> certs(PackageInfo p){Set<String> s=new HashSet<>();android.content.pm.Signature[] signatures=Build.VERSION.SDK_INT>=28?p.signingInfo.getApkContentsSigners():p.signatures;for(var x:signatures)s.add(hex(x.toByteArray()));return s;}
 @SuppressWarnings("deprecation") static void download(Context ctx,JSONObject j)throws Exception{long wanted=j.getLong("size");if(wanted<=0||wanted>100*1024*1024)throw new IOException("Invalid update size.");File target=apk(ctx);File temp=new File(target.getParentFile(),"download.part");HttpURLConnection c=connect(j.getString("url"));MessageDigest digest=MessageDigest.getInstance("SHA-256");long count=0;try(InputStream in=c.getInputStream();OutputStream out=new FileOutputStream(temp)){byte[] buffer=new byte[16384];int n;while((n=in.read(buffer))!=-1){count+=n;if(count>wanted)throw new IOException("Update exceeds expected size.");out.write(buffer,0,n);digest.update(buffer,0,n);}}catch(Exception e){temp.delete();throw e;}finally{c.disconnect();}if(count!=wanted||!hex(digest.digest()).equalsIgnoreCase(j.getString("sha256"))){temp.delete();throw new IOException("Update integrity check failed.");}int flags=Build.VERSION.SDK_INT>=28?PackageManager.GET_SIGNING_CERTIFICATES:PackageManager.GET_SIGNATURES;PackageManager pm=ctx.getPackageManager();PackageInfo incoming=pm.getPackageArchiveInfo(temp.getAbsolutePath(),flags);PackageInfo installed=pm.getPackageInfo(ctx.getPackageName(),flags);long code=incoming==null?0:(Build.VERSION.SDK_INT>=28?incoming.getLongVersionCode():incoming.versionCode);if(incoming==null||!incoming.packageName.equals(ctx.getPackageName())||code!=j.getLong("versionCode")||code<=BuildConfig.VERSION_CODE||!certs(incoming).equals(certs(installed))){temp.delete();throw new IOException("Update package, version or signing identity does not match.");}if(target.exists())target.delete();if(!temp.renameTo(target))throw new IOException("Could not save update.");}
 static void install(Activity a){if(!a.getPackageManager().canRequestPackageInstalls()){new android.app.AlertDialog.Builder(a).setTitle("Allow app updates").setMessage("Allow this app to install updates, then return and tap Check for updates again.").setPositiveButton("Open settings",(d,w)->a.startActivity(new Intent("android.settings.MANAGE_UNKNOWN_APP_SOURCES",Uri.parse("package:"+a.getPackageName())))).setNegativeButton("Cancel",null).show();return;}Uri uri=FileProvider.getUriForFile(a,a.getPackageName()+".files",apk(a));a.startActivity(new Intent(Intent.ACTION_VIEW).setDataAndType(uri,"application/vnd.android.package-archive").addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION));}
}
